export const FETCH_WEATHER_OF_CITY = 'FETCH_WEATHER_OF_CITY';
export const FETCH_WEATHER_OF_CITY_FAIL = "FETCH_WEATHER_OF_CITY_FAIL";
export const FETCH_WEATHER_OF_CITY_PENDING = "FETCH_WEATHER_OF_CITY_PENDING";
export const FETCH_WEATHER_OF_CITY_SUCCESS = "FETCH_WEATHER_OF_CITY_SUCCESS";