export const FETCH_WEATHER_OF_CITY = 'FETCH_WEATHER_OF_CITY';
export const FETCH_WEATHER_OF_CITY_FAIL = "FETCH_WEATHER_OF_CITY_FAIL";
export const FETCH_WEATHER_OF_CITY_PENDING = "FETCH_WEATHER_OF_CITY_PENDING";
export const FETCH_WEATHER_OF_CITY_SUCCESS = "FETCH_WEATHER_OF_CITY_SUCCESS";

export const FETCH_WEATHER_OF_CITIES = 'FETCH_WEATHER_OF_CITIES';
export const FETCH_WEATHER_OF_CITIES_FAIL = "FETCH_WEATHER_OF_CITIES_FAIL";
export const FETCH_WEATHER_OF_CITIES_PENDING = "FETCH_WEATHER_OF_CITIES_PENDING";
export const FETCH_WEATHER_OF_CITIES_SUCCESS = "FETCH_WEATHER_OF_CITIES_SUCCESS";

export const ADD_CITY = 'ADD_CITY';
export const ADD_CITY_SUCCESS = "ADD_CITY_SUCCESS";
export const ADD_CITY_FAIL = "ADD_CITY_FAIL";


export const REMOVE_CITY = 'REMOVE_CITY';
export const REMOVE_CITY_SUCCESS = "REMOVE_CITY_SUCCESS";
export const REMOVE_CITY_FAIL = "REMOVE_CITY_FAIL";

export const FETCH_WEATHER_DETAIL_OF_CITY = 'FETCH_WEATHER_DETAIL_OF_CITY';
export const FETCH_WEATHER_DETAIL_OF_CITY_SUCCESS = "FETCH_WEATHER_DETAIL_OF_CITY_SUCCESS";
export const FETCH_WEATHER_DETAIL_OF_CITY_FAIL = "FETCH_WEATHER_DETAIL_OF_CITY_FAIL";