export const FETCH_TEXT = 'FETCH_TEXT';
export const FETCH_TEXT_FAIL = "FETCH_TEXT_FAIL";
export const FETCH_TEXT_PENDING = "FETCH_TEXT_PENDING";
export const FETCH_TEXT_SUCCESS = "FETCH_TEXT_SUCCESS";